### ISSUE TITLE
Scaling n-gram algorithm

### ISSUE THREAD

**Issue by ARMmaster17** [ARMmaster17/JeffBot#12]
Right now, JeffBot uses bigrams to do language processing. Should it be moved up to N3 at the cost of purging the database and higher training data count requirement.

**Comment by ARMmaster17** [comment]
Going to change from a n2->n5, then scale down if no matches. Will terminate on missing n2 link.

**Comment by ARMmaster17** [comment]
Due to a database issue, changed form N2 to N3 in latest commit. Verifying that there are no bugs before closing issue.

**Comment by FreekingDean** [comment]
I'm not 100% sure, but could this be related to #29?

**Comment by ARMmaster17** [comment]
Yes, this is related to #29. Investigating.

**Comment by FreekingDean** [comment]
So I figured the issue it was in the `formulator.rb` file. It was using the old style bigram call to `Wordchain`

**Comment by FreekingDean** [comment]
JeffBot now is very specific in his responses. I think we should add some randomness into his next choice and not always choose the most popular word.

**Comment by ARMmaster17** [comment]
You may be missing some code, I believe on Saturday (EST), I committed in code that would randomly pick a word to add based on the `count` field. (Higher count, higher probability of being picked).

**Comment by FreekingDean** [comment]
I had just started playing with this Sunday, so I should be up to date. I'll look deeper into it.

**Comment by ARMmaster17** [comment]
See commit 8390e6a095c91130cf4855ea678379de2242a8a1

**Comment by FreekingDean** [comment]
I see! Totally glossed over that. I "Rubified" it a bit to make it a bit more clear and closer to ruby syntax in #31

**Comment by FreekingDean** [comment]
It uses a bit more of a popular random sort.

**Comment by FreekingDean** [comment]
So It will get the group of words and starting with the most popular choice its got a 90% chance of using the first one same for the second and so on. Meaning the first 2 options have a (.90+(.90*.90)) chance and so on for SUM(0-n)(.90x.90^n)

**Comment by FreekingDean** [comment]
I think you can close this if this is for N3 Ngram! :)
