### ISSUE TITLE
JeffBot will go into an infinite loop

### ISSUE THREAD

**Issue by ARMmaster17** [ARMmaster17/JeffBot#5]
If you send a certain message [omitted for resource protection], JeffBot will go into an infinite loop. Need to verify that the sender is not the same as JeffBot.

**Comment by FreekingDean** [comment]
Is this a GroupMe specific bug?

**Comment by ARMmaster17** [comment]
@FreekingDean Yes, this was specific to GroupMe back when JB had a feature where it would repeat after you. I forgot to close this issue.
